#!/bin/bash

echo 'password'
echo 'The rcon_announce shell script has been enabled!'

while true
do
  echo "/say Message one."
  echo "/say Message two."
  echo "/say Message three."
  sleep 30
  echo "/say Message four."
  echo "/say Message five."
  sleep 300
done
