#!/bin/bash
bal_log=/tmp/bal_log
bal_ids=/tmp/bal_ids
alpha=/tmp/alpha
bravo=/tmp/bravo
spectators=/tmp/spectators
players=/tmp/players

echo 'password'
rm -rf $players $alpha $bravo 2> /dev/null
cat /dev/null | tee $bal_log $alpha\_io $alpha\_io2 \
$bravo\_io $bravo\_io2 $spectators\_io > $spectators\_io2
seq 1 32 > $bal_ids
echo 0 | tee $alpha\_count > $bravo\_count
mkdir $alpha $bravo $players 2> /dev/null
echo 'The rcon_balancer shell script has been enabled!'

while true
do
  find $alpha/ | sed -u 1d | wc -l > $alpha\_count
  find $bravo/ | sed -u 1d | wc -l > $bravo\_count
  if grep -qa '^.* joining game (.*) HWID:.*$' $bal_log
  then
    sed -nu '/^.* joining game (.*) HWID:.*$/ s/ joining game .*//p' \
    $bal_log | sed -u 's/[$*[\"^]/\\&/g' > \
    $players/`grep -am1 '^[0-9]' $bal_ids`
    cat /dev/null > $bal_log
    sed -iu "/^`grep -am1 ^[0-9] $bal_ids`$/ s/^/Used /" $bal_ids
  elif grep -qa '^.* has joined alpha team\.$' $bal_log
  then
    sed -nu '/^.* has joined alpha team\.$/ s/ has joined alpha team\.//p' \
    $bal_log | sed -u 's/[$*[\"^]/\\&/g' > $alpha\_io
    cat /dev/null > $bal_log
    link $players/`grep -Ha "\`cat $alpha\_io\`" $players/* | \
    sed "s/:.*//;s/.*[^0-9]//"` $alpha/`grep -Ha "\`cat $alpha\_io\`" \
    $players/* | sed "s/:.*//;s/.*[^0-9]//"` 2> /dev/null
    unlink $bravo/`grep -Ha "\`cat $alpha\_io\`" $players/* | \
    sed "s/:.*//;s/.*[^0-9]//"` 2> /dev/null
  elif grep -qa '^.* has joined bravo team\.$' $bal_log
  then
    sed -nu '/^.* has joined bravo team\.$/ s/ has joined bravo team\.//p' \
    $bal_log | sed -u 's/[$*[\"^]/\\&/g' > $bravo\_io
    cat /dev/null > $bal_log
    link $players/`grep -Ha "\`cat $bravo\_io\`" $players/* | \
    sed "s/:.*//;s/.*[^0-9]//"` $bravo/`grep -Ha "\`cat $bravo\_io\`" \
    $players/* | sed "s/:.*//;s/.*[^0-9]//"` 2> /dev/null
    unlink $alpha/`grep -Ha "\`cat $bravo\_io\`" $players/* | \
    sed "s/:.*//;s/.*[^0-9]//"` 2> /dev/null
  elif grep -qa '^.* has joined spectators\.$' $bal_log
  then
    sed -nu '/^.* has joined spectators\.$/ s/ has joined spectators\.//p' \
    $bal_log | sed -u 's/[$*[\"^]/\\&/g' > $spectators\_io
    cat /dev/null > $bal_log
    unlink $alpha/`grep -Ha "\`cat $spectators\_io\`" $players/* | \
    sed "s/:.*//;s/.*[^0-9]//"` 2> /dev/null
    unlink $bravo/`grep -Ha "\`cat $spectators\_io\`" $players/* | \
    sed "s/:.*//;s/.*[^0-9]//"` 2> /dev/null
  elif grep -qa '^.* has left alpha team\.$' $bal_log
  then
    sed -nu '/^.* has left alpha team\.$/ s/ has left alpha team\.//p' \
    $bal_log | sed -u 's/[$*[\"^]/\\&/g' > $alpha\_io2
    cat /dev/null > $bal_log
    grep -Ha "`cat $alpha\_io2`" $players/* | sed -u 's/:.*//;s/.*[^0-9]//' | \
    sed -iu "/^Used `cat`$/ s/Used //" $bal_ids
    find /tmp/ -name `grep -Ha "\`cat $alpha\_io2\`" $players/* | \
    sed 's/:.*//;s/.*[^0-9]//'` -exec unlink '{}' \; 2> /dev/null
  elif grep -qa '^.* has left bravo team\.$' $bal_log
  then
    sed -nu '/^.* has left bravo team\.$/ s/ has left bravo team\.//p' \
    $bal_log | sed -u 's/[$*[\"^]/\\&/g' > $bravo\_io2
    cat /dev/null > $bal_log
    grep -Ha "`cat $bravo\_io2`" $players/* | sed -u 's/:.*//;s/.*[^0-9]//' | \
    sed -iu "/^Used `cat`$/ s/Used //" $bal_ids
    find /tmp/ -name `grep -Ha "\`cat $bravo\_io2\`" $players/* | \
    sed 's/:.*//;s/.*[^0-9]//'` -exec unlink '{}' \; 2> /dev/null
  elif grep -qa '^.* has left spectators$' $bal_log
  then
    sed -nu '/^.* has left spectators$/ s/ has left spectators//p' \
    $bal_log | sed -u 's/[$*[\"^]/\\&/g' > $spectators\_io2
    cat /dev/null > $bal_log
    grep -Ha "`cat $spectators\_io2`" $players/* | sed -u 's/:.*//;s/.*[^0-9]//' | \
    sed -iu "/^Used `cat`$/ s/Used //" $bal_ids
    find /tmp/ -name `grep -Ha "\`cat $spectators\_io2\`" $players/* | \
    sed 's/:.*//;s/.*[^0-9]//'` -exec unlink '{}' \; 2> /dev/null
  elif [[ `dc -e "\`cat $alpha\_count\` \`cat $bravo\_count\` - p"` -ge 2 ]]
  then
    ls $alpha/ | sort | tail -n1 | sed -u 's/^/\/setteam2 /'
    ls $alpha/ | sort | tail -n1 | unlink $alpha/`cat`
  elif [[ `dc -e "\`cat $bravo\_count\` \`cat $alpha\_count\` - p"` -ge 2 ]]
  then
    ls $bravo/ | sort | tail -n1 | sed -u 's/^/\/setteam1 /'
    ls $bravo/ | sort | tail -n1 | unlink $bravo/`cat`
  fi
done
