#!/bin/bash
bal_log=/tmp/bal_log
bal_ids=/tmp/bal_ids
alpha=/tmp/alpha
bravo=/tmp/bravo
spectators=/tmp/spectators
players=/tmp/players

echo 'password'
rm -rf $players $alpha $bravo 2> /dev/null
cat /dev/null | tee $bal_log $alpha\_io $alpha\_io2 \
$bravo\_io $bravo\_io2 $spectators\_io > $spectators\_io2
seq 1 32 > $bal_ids
echo 0 | tee $alpha\_count > $bravo\_count
mkdir $alpha $bravo $players 2> /dev/null
echo 'The rcon_balancer shell script has been enabled!'

while true
do
  find $alpha/ | sed -u 1d | wc -l > $alpha\_count
  find $bravo/ | sed -u 1d | wc -l > $bravo\_count
  if grep -qa '^.* joining game (.*) HWID:.*$' $bal_log
  then
    sed -nu '/^.* joining game (.*) HWID:.*$/ s/ joining game .*//p' \
    $bal_log | sed -u 's/[$*[\"^]/\\&/g' > $players\_io
    cat /dev/null > $bal_log
    grep -am1 '^[0-9]' $bal_ids > "$players/`cat $players\_io`"
    sed -iu "/^`grep -am1 ^[0-9] $bal_ids`$/ s/^/Used /" $bal_ids
  elif grep -qa '^.* has joined alpha team\.$' $bal_log
  then
    sed -nu '/^.* has joined alpha team\.$/ s/ has joined alpha team\.//p' \
    $bal_log | sed -u 's/[$*[\"^]/\\&/g' > $alpha\_io
    cat /dev/null > $bal_log
    link "$players/`cat $alpha\_io`" "$alpha/`cat $alpha\_io`"
    unlink "$bravo/`cat $alpha\_io`" 2> /dev/null
  elif grep -qa '^.* has joined bravo team\.$' $bal_log
  then
    sed -nu '/^.* has joined bravo team\.$/ s/ has joined bravo team\.//p' \
    $bal_log | sed -u 's/[$*[\"^]/\\&/g' > $bravo\_io
    cat /dev/null > $bal_log
    link "$players/`cat $bravo\_io`" "$bravo/`cat $bravo\_io`"
    unlink "$alpha/`cat $bravo\_io`" 2> /dev/null
  elif grep -qa '^.* has joined spectators\.$' $bal_log
  then
    sed -nu '/^.* has joined spectators\.$/ s/ has joined spectators\.//p' \
    $bal_log | sed -u 's/[$*[\"^]/\\&/g' > $spectators\_io
    cat /dev/null > $bal_log
    unlink "$alpha/`cat $spectators\_io`" 2> /dev/null
    unlink "$bravo/`cat $spectators\_io`" 2> /dev/null
  elif grep -qa '^.* has left alpha team\.$' $bal_log
  then
    sed -nu '/^.* has left alpha team\.$/ s/ has left alpha team\.//p' \
    $bal_log | sed -u 's/[$*[\"^]/\\&/g' > $alpha\_io2
    cat /dev/null > $bal_log
    cat $players/"`cat $alpha\_io2`" > $bal_ids\_io
    sed -iu "/`cat $bal_ids\_io`/ s/Used //" $bal_ids
    find /tmp/ -name "`cat $alpha\_io2`" -exec unlink '{}' \; 2> /dev/null
  elif grep -qa '^.* has left bravo team\.$' $bal_log
  then
    sed -nu '/^.* has left bravo team\.$/ s/ has left bravo team\.//p' \
    $bal_log | sed -u 's/[$*[\"^]/\\&/g' > $bravo\_io2
    cat /dev/null > $bal_log
    cat $players/"`cat $bravo\_io2`" > $bal_ids\_io
    sed -iu "/`cat $bal_ids\_io`/ s/Used //" $bal_ids
    find /tmp/ -name "`cat $bravo\_io2`" -exec unlink '{}' \; 2> /dev/null
  elif grep -qa '^.* has left spectators$' $bal_log
  then
    sed -nu '/^.* has left spectators$/ s/ has left spectators//p' \
    $bal_log | sed -u 's/[$*[\"^]/\\&/g' > $spectators\_io2
    cat /dev/null > $bal_log
    cat $players/"`cat $spectators\_io2`" > $bal_ids\_io
    sed -iu "/`cat $bal_ids\_io`/ s/Used //" $bal_ids
    find /tmp/ -name "`cat $spectators\_io2`" -exec unlink '{}' \; 2> /dev/null
  elif [[ `dc -e "\`cat $alpha\_count\` \`cat $bravo\_count\` - p"` -ge 2 ]]
  then
    sed -nu '$s/^/\/setteam2 /p' $alpha/"`cat $alpha\_io`"
    unlink "$alpha/`cat $alpha\_io`" 2> /dev/null
  elif [[ `dc -e "\`cat $bravo\_count\` \`cat $alpha\_count\` - p"` -ge 2 ]]
  then
    sed -nu '$s/^/\/setteam1 /p' $bravo/"`cat $bravo\_io`"
    unlink "$bravo/`cat $bravo\_io`" 2> /dev/null
  fi
done
