#!/bin/bash
cmds=/tmp/cmds

echo 'password'
cat /dev/null > $cmds
echo 'The rcon_commands shell script has been enabled!'

while true
do
  if grep -qa '^\[.*] !cmds$' $cmds
  then
    cat /dev/null > $cmds
    echo "/say !date, !info, !script, !red, !blue, !spec"
  elif grep -qa '^\[.*] !script$' $cmds || \
  grep -qa '^\[.*] !license$' $cmds || \
  grep -qa '^\[.*] !source$' $cmds
  then
    cat /dev/null > $cmds
    echo "/say Soldat Shell - A Unix shell script made by a Unix guru."
    echo "/say Soldat Shell is released under the terms of the GNU AGPLv3 license."
    echo "/say You may ask an administrator for the modified source code of this program."
    echo "/say The original source code can be found at: https://github.com/Krush206/soldat-shell"
  elif grep -qa '^\[.*] !date$' $cmds
  then
    cat /dev/null > $cmds
    echo "/say `date`"
  elif grep -qa '^\[.*] !info$' $cmds
  then
    cat /dev/null > $cmds
    echo "/say `uname -a`"
  elif grep -qa '^\[.*] !red$' $cmds || grep -qa '^\[.*] !1$' $cmds
  then
    sed -nu '/^\[.*] !.*$/p' $cmds | sed -u 's/^./\/setteam1 /;s/....$//'
    cat /dev/null > $cmds
  elif grep -qa '^\[.*] !blue$' $cmds || grep -qa '^\[.*] !2$' $cmds
  then
    sed -nu '/^\[.*] !.*$/p' $cmds | sed -u 's/^./\/setteam2 /;s/....$//'
    cat /dev/null > $cmds
  elif grep -qa '^\[.*] !spec$' $cmds || grep -qa '^\[.*] !5$' $cmds
  then
    sed -nu '/^\[.*] !.*$/p' $cmds | sed -u 's/^./\/setteam5 /;s/....$//'
    cat /dev/null > $cmds
  fi
done
