#!/bin/tcsh -f
if (`uname -s` == Linux) then
  setenv sedimp 'sed -i'
else if (`uname -s` == FreeBSD || `uname -s` == NetBSD || \
`uname -s` == DragonFlyBSD || `uname -s` == OpenBSD) then
  setenv sedimp 'sed -i '\'''\'''
endif

setenv kill_count /tmp/kill_count
setenv killer /tmp/killer
: > $kill_count\_check
: > $killer\_list
mkfifo $killer\_clear >& /dev/null
rm -f $killer\_team

echo "$1" # RCON password
echo 'The rcon_kills C shell script has been enabled!'

kill_log:
  setenv kill_log "$<"

if ( { ( echo -n "$kill_log" | grep -qa '^.* joining game.*HWID:.*$' ) } && ! \
  { ( echo -n "$kill_log" | \
  sed -u 's/^\[//;s/].*$//' | grep -Fqxaf $killer\_list ) } && ! \
  { ( echo -n "$kill_log" | \
  sed -u 's/ joining game .*//' | grep -Fqxaf $killer\_list ) } ) then
  echo "$kill_log" | \
  sed -u 's/ joining game .*//' >> $killer\_list
else if ( { ( echo -n "$kill_log" | grep -qa '^.* killed .* with .*$' ) } && \
  { ( echo -n "$kill_log" | \
  sed -u 's/ killed .* with .*$//' | grep -Fqxaf $killer\_list || \
  echo -n "$kill_log" | tee $killer\_team | \
  sed -u 's/^([0-9]) //;s/ killed ([0-9]) .* with .*$//' | grep -Fqxaf $killer\_list ) } && \
  { ( echo -n "$kill_log" | \
  sed -u 's/ with .*$//;s/.* killed //' | grep -Fqxaf $killer\_list || \
  echo -n "$kill_log" | tee $killer\_team | \
  sed -u 's/^([0-9]) .* killed ([0-9]) //;s/ with .*$//' | grep -Fqxaf $killer\_list ) } ) then
  if ( -e $killer\_team ) then
    echo "$kill_log" | \
    sed -u 's/^([0-9]) //;s/ killed ([0-9]) .* with .*$//' | tee $killer >> $kill_count\_check
    echo "$kill_log" | \
    sed -u 's/^([0-9]) .* killed ([0-9]) //;s/ with .*$//' > $killer\_clear &
  else
    echo "$kill_log" | \
    sed -u 's/ killed .* with .*$//' | tee $killer >> $kill_count\_check
    echo "$kill_log" | \
    sed -u 's/ with .*$//;s/.* killed //' > $killer\_clear &
  endif
  eval $sedimp '"/^`tee < $killer\_clear`"\$"/d"' $kill_count\_check
  sort $kill_count\_check | uniq -c | sed -u 's/^ *//' > $kill_count
  if ( { ( grep -qa "^5 `tee < $killer`" $kill_count ) } ) then
    sed -nu "/^5 `tee < $killer`/p" $kill_count | sed -u 's/^../\/say /;s/$/ is a killer\!/'
  else if ( { ( grep -qa "^8 `tee < $killer`" $kill_count ) } ) then
    sed -nu "/^8 `tee < $killer`/p" $kill_count | sed -u 's/^../\/say /;s/$/ is violent\!/'
  else if ( { ( grep -qa "^11 `tee < $killer`" $kill_count ) } ) then
    sed -nu "/^11 `tee < $killer`/p" $kill_count | sed -u 's/^.../\/say /;s/$/ is dominating\!/'
  else if ( { ( grep -qa "^14 `tee < $killer`" $kill_count ) } ) then
    sed -nu "/^14 `tee < $killer`/p" $kill_count | sed -u 's/^.../\/say /;s/$/ is crazy\!/'
  else if ( { ( grep -qa "^17 `tee < $killer`" $kill_count ) } ) then
    sed -nu "/^17 `tee < $killer`/p" $kill_count | sed -u 's/^.../\/say /;s/$/ is taking over\!/'
  else if ( { ( grep -qa "^20 `tee < $killer`" $kill_count ) } ) then
    sed -nu "/^20 `tee < $killer`/p" $kill_count | sed -u 's/^.../\/say /;s/$/ is unstoppable\!/'
  else if ( { ( grep -qa "^22 `tee < $killer`" $kill_count ) } ) then
    sed -nu "/^22 `tee < $killer`/p" $kill_count | sed -u 's/^.../\/say /;s/$/ is a god\!/'
  else if ( { ( grep -qa "^25 `tee < $killer`" $kill_count ) } ) then
    sed -nu "/^25 `tee < $killer`/p" $kill_count | sed -u 's/^.../\/say /;s/$/ is a cheater\!\!/'
  else if ( { ( grep -qa "^27 `tee < $killer`" $kill_count ) } ) then
    sed -nu "/^27 `tee < $killer`/p" $kill_count | sed -u 's/^.../\/say /;s/$/, dude, stop it\!\!\!/'
  endif
endif
goto kill_log
