#!/bin/tcsh -f

setenv kill_count /tmp/kill_count
setenv killer /tmp/killer
: > $kill_count\_check
: > $killer\_list
mkfifo $killer\_clear >& /dev/null
rm -f $killer\_team

echo "$1" # RCON password
echo 'The rcon_kills C shell script has been enabled!'

kill_log:
  setenv kill_log "$<"

if ( { ( echo -n "$kill_log" | \
  grep -qa '^.* joining game ([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*:[0-9]*) HWID:.*$' ) } && ! \
  { ( echo -n "$kill_log" | \
  sed -u 's/^\[//;s/].*$//' | grep -Fqxaf $killer\_list ) } && ! \
  { ( echo -n "$kill_log" | \
  sed -u 's/ joining game .*//' | grep -Fqxaf $killer\_list ) } ) then
  echo "$kill_log" | \
  sed -u 's/ joining game .*//' >> $killer\_list
else if ( { ( echo -n "$kill_log" | grep -qa '^.* killed .* with .*$' ) } && \
  { ( echo -n "$kill_log" | \
  sed -u 's/ killed .* with .*$//' | grep -Fqxaf $killer\_list || \
  echo -n "$kill_log" | tee $killer\_team | \
  sed -u 's/^([0-9]) //;s/ killed ([0-9]) .* with .*$//' | grep -Fqxaf $killer\_list ) } && \
  { ( echo -n "$kill_log" | \
  sed -u 's/ with .*$//;s/.* killed //' | grep -Fqxaf $killer\_list || \
  echo -n "$kill_log" | tee $killer\_team | \
  sed -u 's/^([0-9]) .* killed ([0-9]) //;s/ with .*$//' | grep -Fqxaf $killer\_list ) } ) then
  if ( -e $killer\_team ) then
    echo "$kill_log" | \
    sed -u 's/^([0-9]) //;s/ killed ([0-9]) .* with .*$//' | tee $killer >> $kill_count\_check
    echo "$kill_log" | \
    sed -u 's/^([0-9]) .* killed ([0-9]) //;s/ with .*$//' > $killer\_clear &
  else
    echo "$kill_log" | \
    sed -u 's/ killed .* with .*$//' | tee $killer >> $kill_count\_check
    echo "$kill_log" | \
    sed -u 's/ with .*$//;s/.* killed //' > $killer\_clear &
  endif
  cat < $kill_count\_check > $kill_count\_new
  grep -Fxavf $killer\_clear $kill_count\_new > $kill_count\_check
  sort $kill_count\_check | uniq -c | sed -u 's/^ *//' > $kill_count
  if ( { ( sed -u 's/^/5 /' < $killer | grep -Fxqaf $kill_count ) } ) then
    sed -u 's/^/\/say /;s/$/ is a killer\!/' < $killer
  else if ( { ( sed -u 's/^/8 /' < $killer | grep -Fxqaf $kill_count ) } ) then
    sed -u 's/^/\/say /;s/$/ is violent\!/' < $killer
  else if ( { ( sed -u 's/^/11 /' < $killer | grep -Fxqaf $kill_count ) } ) then
    sed -u 's/^/\/say /;s/$/ is dominating\!/' < $killer
  else if ( { ( sed -u 's/^/14 /' < $killer | grep -Fxqaf $kill_count ) } ) then
    sed -u 's/^/\/say /;s/$/ is crazy\!/' < $killer
  else if ( { ( sed -u 's/^/17 /' < $killer | grep -Fxqaf $kill_count ) } ) then
    sed -u 's/^/\/say /;s/$/ is taking over\!/' < $killer
  else if ( { ( sed -u 's/^/20 /' < $killer | grep -Fxqaf $kill_count ) } ) then
    sed -u 's/^/\/say /;s/$/ is unstoppable\!/' < $killer
  else if ( { ( sed -u 's/^/22 /' < $killer | grep -Fxqaf $kill_count ) } ) then
    sed -u 's/^/\/say /;s/$/ is a god\!/' < $killer
  else if ( { ( sed -u 's/^/25 /' < $killer | grep -Fxqaf $kill_count ) } ) then
    sed -u 's/^/\/say /;s/$/ is a cheater\!\!/' < $killer
  else if ( { ( sed -u 's/^/27 /' < $killer | grep -Fxqaf $kill_count ) } ) then
    sed -u 's/^/\/say /;s/$/, dude, stop it\!\!\!/' < $killer
  endif
endif
goto kill_log
